<?xml version="1.0"?>
<robot>

  <link name="rotational_robot_holder_base">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${rotational_robot_holder_base_length}" radius="${rotational_robot_holder_base_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${rotational_robot_holder_base_length}" radius="${rotational_robot_holder_base_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <mass value="10"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
    </inertial>

  </link>

  <link name="rotational_robot_holder_virtual">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <sphere radius="0.01"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    
  </link>

  <link name="rotational_robot_holder_holder">
    <collision>
      <origin xyz="${rotational_robot_holder_holder_length/2} 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder length="${rotational_robot_holder_holder_length}" radius="${rotational_robot_holder_holder_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${rotational_robot_holder_holder_length/2} 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
         <cylinder length="${rotational_robot_holder_holder_length}" radius="${rotational_robot_holder_holder_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    
  </link>

  <!-- Robot to rotational_robot_holder -->

  <joint name="rotational_robot_holder_base_to_world" type="fixed">
    <parent link="world"/>
    <child link="rotational_robot_holder_base"/>
    <origin xyz="0 0 ${rotational_robot_holder_base_length/2}" rpy="0 0 0"/>
  </joint>

  <joint name="rotational_robot_holder_virtual_to_holder" type="continuous">
    <parent link="rotational_robot_holder_base"/>
    <child link="rotational_robot_holder_virtual"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint> 

  <joint name="rotational_robot_holder_joint" type="continuous">
    <parent link="rotational_robot_holder_virtual"/>
    <child link="rotational_robot_holder_holder"/>
    <origin xyz="0 0 ${rotational_robot_holder_base_length/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <joint name="rotational_robot_holder_to_rotot" type="fixed">
    <parent link="rotational_robot_holder_holder"/>
    <child link="body"/>
    <origin xyz="${rotational_robot_holder_holder_length+bodyWidth/2} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="30" velocity="1.0" lower="0" upper="1" />
  </joint> 

</robot>