dacbot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers 
  left_ankle_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_ankle
  left_knee_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_knee
  left_hip_position_controller:
    type: effort_controllers/JointEffortController
    joint: left_hip

  right_ankle_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_ankle
  right_knee_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_knee
  right_hip_position_controller:
    type: effort_controllers/JointEffortController
    joint: right_hip
