<?xml version="1.0"?>

<robot name="dacbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Constants -->
	<xacro:property name="PI" value="3.1415926535897931"/>

	<!-- Robot configuration 
		Width = X axis
		Length = Y axis
		Height = Z axis
	-->
	<xacro:property name="scale" value="1" />

	<xacro:property name="bodyWidth" value="0.085" />
	<xacro:property name="bodyLength" value="0.08" />
	<xacro:property name="bodyHeight" value="0.065" />
	<xacro:property name="bodyMass" value="0.45" />

	<xacro:property name="weightWidth" value="0.05" />
	<xacro:property name="weightLength" value="0.07" />
	<xacro:property name="weightHeight" value="0.025" />
	<xacro:property name="weightMass" value="0.50" />

	<xacro:property name="upperLegWidth" value="0.015" />
	<xacro:property name="upperLegLength" value="0.015" />
	<xacro:property name="upperLegHeight" value="0.142" />
	<xacro:property name="upperLegMass" value="0.2" />

	<xacro:property name="lowerLegWidth" value="0.015" />
	<xacro:property name="lowerLegLength" value="0.015" />
	<xacro:property name="lowerLegHeight" value="0.125" />
	<xacro:property name="lowerLegMass" value="0.08" />

	<xacro:property name="footWidth" value="0.015" />
	<xacro:property name="footLength" value="0.050" />
	<xacro:property name="footHeight" value="0.008" />
	<xacro:property name="footMass" value="0.01" />

	<xacro:property name="legDistFromCenter" value="0.015" />

	<xacro:property name="footAnklePos" value="0.015" />
	<xacro:property name="legAnklePos" value="0" />
	<xacro:property name="lowerKneePos" value="0.12" />
	<xacro:property name="upperKneePos" value="0.02" />
	<xacro:property name="legHipPos" value="0.132" />
	<xacro:property name="bodyHipHeight" value="0.01" />
	<xacro:property name="bodyHipWidth" value="0.025" />

	<xacro:property name="massJointBodyDepth" value="0.07" />
	<xacro:property name="massJointBodyHeight" value="0.055" />
	<xacro:property name="massJointMassDepth" value="0.065" />
	<xacro:property name="massJointMassHeigth" value="0.007" />

	<xacro:property name="armLength" value="0.6" />
	<xacro:property name="armOffset" value="0.025" />


	<!-- Import Gazebo customizations and colors-->
	<xacro:include filename="$(find dacbot_description)/urdf/dacbot.gazebo" />
	<xacro:include filename="$(find dacbot_description)/urdf/colors.xacro" />



	<!-- 
		Macros
	 -->

	 <!-- Box Macro! 
	<xacro:create_box name="" origin_x="" origin_y="" origin_z="" r="" p="" y="" width="" length="" height="" mass="" />
	 -->
	<xacro:macro name="create_box" params="name origin_x origin_y origin_z r p y width length height mass">
		<link name="${name}">
			<collision>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="${r} ${p} ${y}"/>
				<geometry>
					<box size="${width*scale} ${length*scale} ${height*scale}" />
				</geometry>
			</collision>

			<visual>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="${r} ${p} ${y}"/>
				<geometry>
					<box size="${width*scale} ${length*scale} ${height*scale}" />
				</geometry>
				<material name="orange"/>
			</visual>

			<inertial>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="${r} ${p} ${y}"/>
				<mass value="${mass}"/>
				<inertia
					ixx="${mass / 12.0 * (length*length + height*height)*scale*scale}" ixy="0.0" ixz="0.0" 
					iyy="${mass / 12.0 * (height*height + width*width)*scale*scale}" iyz="0.0" 
					izz="${mass / 12.0 * (width*width + length*length)*scale*scale}"/>
			</inertial>
		</link>
	</xacro:macro>

	<!-- 
		World
	-->
	<!-- <link name="dacbot_global"/> -->

	<!-- 
		Left Leg
	-->

	<!-- Left Foot -->
	<xacro:create_box name="left_foot" origin_x="${footHeight*scale/2}" origin_y="${footLength*scale/2 - footAnklePos}" origin_z="0" r="0" p="${-PI/2}" y="0" width="${footWidth}" length="${footLength}" height="${footHeight}" mass="${footMass}" />

	<!-- Left Lower Leg -->
	<xacro:create_box name="left_lower_leg" origin_x="${lowerLegHeight*scale/2}" origin_y="0" origin_z="0" r="0" p="${-PI/2}" y="0" width="${lowerLegWidth}" length="${lowerLegLength}" height="${lowerLegHeight}" mass="${lowerLegMass}" />

	<!-- Left Upper Leg -->
	<xacro:create_box name="left_upper_leg" origin_x="${upperLegHeight*scale/2}" origin_y="0" origin_z="0" r="0" p="${-PI/2}" y="0" width="${upperLegWidth}" length="${upperLegLength}" height="${upperLegHeight}" mass="${upperLegMass}" />


	<!-- 
		Right Leg
	-->
	<!-- Right Foot -->
	<xacro:create_box name="right_foot" origin_x="${footHeight*scale/2}" origin_y="${footLength*scale/2 - footAnklePos}" origin_z="0" r="0" p="${-PI/2}" y="0" width="${footWidth}" length="${footLength}" height="${footHeight}" mass="${footMass}" />

	<!-- Right Lower Leg -->
	<xacro:create_box name="right_lower_leg" origin_x="${lowerLegHeight*scale/2}" origin_y="0" origin_z="0" r="0" p="${-PI/2}" y="0" width="${lowerLegWidth}" length="${lowerLegLength}" height="${lowerLegHeight}" mass="${lowerLegMass}" />

	<!-- Right Upper Leg -->
	<xacro:create_box name="right_upper_leg" origin_x="${upperLegHeight*scale/2}" origin_y="0" origin_z="0" r="0" p="${-PI/2}" y="0" width="${upperLegWidth}" length="${upperLegLength}" height="${upperLegHeight}" mass="${upperLegMass}" />


	<!-- 
		Body
	-->
	<xacro:create_box name="body" origin_x="0" origin_y="0" origin_z="${bodyHeight/2}" r="0" p="0" y="0" width="${bodyWidth}" length="${bodyLength}" height="${bodyHeight}" mass="${bodyMass}" />

	<!-- 
		Origin
	-->
	<link name="dacbot_origin"/>


	<!-- 
		Joints 
	-->
	<joint name="dacbot" type="fixed">
		<parent link="dacbot_origin"/>
		<child link="body" />
		<origin xyz="0 0 ${(bodyHeight*scale/2 + footHeight - legAnklePos + lowerKneePos - upperKneePos + legHipPos - bodyHipHeight)*2}" rpy="0 0 0"/>
	</joint>

	<joint name="left_hip" type="continuous">
		<parent link="body"/>
		<child link="left_upper_leg"/>
		<origin xyz="${-legDistFromCenter} 0 0" rpy="0 ${PI/2} 0"/>
		<axis xyz="0 0 1"/>
		<dynamics damping="0.7"/>
	</joint> 

	<joint name="left_knee" type="continuous">
		<parent link="left_upper_leg"/>
		<child link="left_lower_leg"/>
		<origin xyz="${upperLegHeight} 0 0" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
		<dynamics damping="0.7"/>
	</joint>

	<joint name="left_ankle" type="continuous">
		<parent link="left_lower_leg"/>
		<child link="left_foot"/>
		<origin xyz="${lowerLegHeight} 0 0" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
		<dynamics damping="0.7"/>
	</joint> 

	<joint name="right_hip" type="continuous">
		<parent link="body"/>
		<child link="right_upper_leg"/>
		<origin xyz="${legDistFromCenter} 0 0" rpy="0 ${PI/2} 0"/>
		<axis xyz="0 0 1"/>
		<dynamics damping="0.7"/>
	</joint> 

	<joint name="right_knee" type="continuous">
		<parent link="right_upper_leg"/>
		<child link="right_lower_leg"/>
		<origin xyz="${upperLegHeight} 0 0" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
		<dynamics damping="0.7"/>
	</joint>

	<joint name="right_ankle" type="continuous">
		<parent link="right_lower_leg"/>
		<child link="right_foot"/>
		<origin xyz="${lowerLegHeight} 0 0" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
		<dynamics damping="0.7"/>
	</joint> 

	<transmission name="left_hip_trans">
		<type>transmission_interface/SimpleTransmission</type>
			<joint name="left_hip">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="left_hip_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="left_knee_trans">
		<type>transmission_interface/SimpleTransmission</type>
			<joint name="left_knee">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="left_knee_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="left_ankle_trans">
		<type>transmission_interface/SimpleTransmission</type>
			<joint name="left_ankle">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="left_ankle_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="right_hip_trans">
		<type>transmission_interface/SimpleTransmission</type>
			<joint name="right_hip">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="right_hip_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="right_knee_trans">
		<type>transmission_interface/SimpleTransmission</type>
			<joint name="right_knee">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="right_knee_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<transmission name="right_ankle_trans">
		<type>transmission_interface/SimpleTransmission</type>
			<joint name="right_ankle">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="right_ankle_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>







</robot>