<?xml version="1.0"?>

<robot name="dacbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Constants -->
	<xacro:property name="PI" value="3.1415926535897931"/>

	<!-- Robot configuration 
		Width = X axis
		Length = Y axis
		Height = Z axis
	-->
	<xacro:property name="scale" value="1" />

	<xacro:property name="bodyWidth" value="0.085" />
	<xacro:property name="bodyLength" value="0.08" />
	<xacro:property name="bodyHeight" value="0.065" />
	<xacro:property name="bodyMass" value="0.45" />

	<xacro:property name="weightWidth" value="0.05" />
	<xacro:property name="weightLength" value="0.07" />
	<xacro:property name="weightHeight" value="0.025" />
	<xacro:property name="weightMass" value="0.50" />

	<xacro:property name="upperLegWidth" value="0.015" />
	<xacro:property name="upperLegLength" value="0.015" />
	<xacro:property name="upperLegHeight" value="0.142" />
	<xacro:property name="upperLegMass" value="0.2" />

	<xacro:property name="lowerLegWidth" value="0.015" />
	<xacro:property name="lowerLegLength" value="0.015" />
	<xacro:property name="lowerLegHeight" value="0.125" />
	<xacro:property name="lowerLegMass" value="0.08" />

	<xacro:property name="footWidth" value="0.015" />
	<xacro:property name="footLength" value="0.050" />
	<xacro:property name="footHeight" value="0.008" />
	<xacro:property name="footMass" value="0.01" />

	<xacro:property name="legDistFromCenter" value="0.015" />

	<xacro:property name="footAnklePos" value="0.015" />
	<xacro:property name="legAnklePos" value="0" />
	<xacro:property name="lowerKneePos" value="0.12" />
	<xacro:property name="upperKneePos" value="0.02" />
	<xacro:property name="legHipPos" value="0.132" />
	<xacro:property name="bodyHipHeight" value="0.01" />
	<xacro:property name="bodyHipWidth" value="0.025" />

	<xacro:property name="massJointBodyDepth" value="0.07" />
	<xacro:property name="massJointBodyHeight" value="0.055" />
	<xacro:property name="massJointMassDepth" value="0.065" />
	<xacro:property name="massJointMassHeigth" value="0.007" />

	<xacro:property name="armLength" value="0.6" />
	<xacro:property name="armOffset" value="0.025" />


	<!-- Import Gazebo customizations and colors-->
	<xacro:include filename="$(find dacbot_description)/urdf/dacbot.gazebo" />
	<xacro:include filename="$(find dacbot_description)/urdf/colors.xacro" />



	<!-- 
		Macros
	 -->

	 <!-- Box Macro! 
	<xacro:create_box name="" origin_x="" origin_y="" origin_z="" width="" length="" height="" mass="" />
	 -->
	<xacro:macro name="create_box" params="name origin_x origin_y origin_z width length height mass">
		<link name="${name}">
			<collision>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>
				<geometry>
					<box size="${width*scale} ${length*scale} ${height*scale}" />
				</geometry>
			</collision>

			<visual>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>
				<geometry>
					<box size="${width*scale} ${length*scale} ${height*scale}" />
				</geometry>
				<material name="orange"/>
			</visual>

			<inertial>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>
				<mass value="${mass}"/>
				<inertia
					ixx="${mass / 12.0 * (length*length + height*height)*scale*scale}" ixy="0.0" ixz="0.0" 
					iyy="${mass / 12.0 * (height*height + width*width)*scale*scale}" iyz="0.0" 
					izz="${mass / 12.0 * (width*width + length*length)*scale*scale}"/>
			</inertial>
		</link>
	</xacro:macro>


	<!-- 
		Left Leg
	-->

	<!-- Left Foot -->
	<xacro:create_box name="left_foot" origin_x="${-legDistFromCenter}" origin_y="${footLength*scale/2 - footAnklePos}" origin_z="${footHeight/2}" width="${footWidth}" length="${footLength}" height="${footHeight}" mass="${footMass}" />

	<!-- Left Lower Leg -->
	<xacro:create_box name="left_lower_leg" origin_x="${-legDistFromCenter}" origin_y="0" origin_z="${lowerLegHeight/2 + footHeight - legAnklePos}" width="${lowerLegWidth}" length="${lowerLegLength}" height="${lowerLegHeight}" mass="${lowerLegMass}" />

	<!-- Left Upper Leg -->
	<xacro:create_box name="left_upper_leg" origin_x="${-legDistFromCenter}" origin_y="0" origin_z="${upperLegHeight/2 + footHeight - legAnklePos + lowerKneePos - upperKneePos}" width="${upperLegWidth}" length="${upperLegLength}" height="${upperLegHeight}" mass="${upperLegMass}" />


	<!-- 
		Right Leg
	-->
	<!-- Right Foot -->
	<xacro:create_box name="right_foot" origin_x="${legDistFromCenter}" origin_y="${footLength*scale/2 - footAnklePos}" origin_z="${footHeight/2}" width="${footWidth}" length="${footLength}" height="${footHeight}" mass="${footMass}" />

	<!-- Right Lower Leg -->
	<xacro:create_box name="right_lower_leg" origin_x="${legDistFromCenter}" origin_y="0" origin_z="${lowerLegHeight/2 + footHeight - legAnklePos}" width="${lowerLegWidth}" length="${lowerLegLength}" height="${lowerLegHeight}" mass="${lowerLegMass}" />

	<!-- Right Upper Leg -->
	<xacro:create_box name="right_upper_leg" origin_x="${legDistFromCenter}" origin_y="0" origin_z="${upperLegHeight/2 + footHeight - legAnklePos + lowerKneePos - upperKneePos}" width="${upperLegWidth}" length="${upperLegLength}" height="${upperLegHeight}" mass="${upperLegMass}" />


	<!-- 
		Body
	-->
	<xacro:create_box name="body" origin_x="0" origin_y="${bodyWidth/2 - bodyHipWidth}" origin_z="${bodyHeight/2 + footHeight - legAnklePos + lowerKneePos - upperKneePos + legHipPos - bodyHipHeight}" width="${bodyWidth}" length="${bodyLength}" height="${bodyHeight}" mass="${bodyMass}" />


	<!-- 
		Joints 
	-->

	<!-- Used for fixing robot to Gazebo 'base_link' -->
	<link name="world"/>

	<joint name="world_left_foot" type="floating">
		<parent link="world"/>
		<child link="left_foot"/>
	</joint>

	<joint name="world_right_foot" type="floating">
		<parent link="world"/>
		<child link="right_foot"/>
	</joint>

	<joint name="left_ankle" type="continuous">
		<parent link="left_foot"/>
		<child link="left_lower_leg"/>
		<origin xyz="${-legDistFromCenter} 0 ${footHeight/2}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>
	</joint> 

	<joint name="left_knee" type="fixed">
		<parent link="left_lower_leg"/>
		<child link="left_upper_leg"/>
		<origin xyz="${-legDistFromCenter} 0 0" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>
	</joint>

	<joint name="left_hip" type="continuous">
		<parent link="left_upper_leg"/>
		<child link="body"/>
		<origin xyz="${-legDistFromCenter} 0 0" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>
	</joint> 

	<joint name="right_ankle" type="continuous">
		<parent link="right_foot"/>
		<child link="right_lower_leg"/>
		<origin xyz="${-legDistFromCenter} 0 ${footHeight/2}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>
	</joint> 

	<joint name="right_knee" type="fixed">
		<parent link="right_lower_leg"/>
		<child link="right_upper_leg"/>
		<origin xyz="${-legDistFromCenter} 0 0" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>
	</joint>

	<joint name="right_hip" type="continuous">
		<parent link="right_upper_leg"/>
		<child link="body"/>
		<origin xyz="${-legDistFromCenter} 0 0" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>
	</joint>

</robot>
