<?xml version="1.0"?>

<robot name="dacbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Constants -->
	<xacro:property name="PI" value="3.1415926535897931"/>

	<!-- Robot configuration 
		Width = X axis
		Length = Y axis
		Height = Z axis
	-->
	<xacro:property name="scale" value="1" />

	<xacro:property name="bodyWidth" value="0.085" />
	<xacro:property name="bodyLength" value="0.08" />
	<xacro:property name="bodyHeight" value="0.065" />
	<xacro:property name="bodyMass" value="0.45" />

	<xacro:property name="weightWidth" value="0.05" />
	<xacro:property name="weightLength" value="0.07" />
	<xacro:property name="weightHeight" value="0.025" />
	<xacro:property name="weightMass" value="0.50" />

	<xacro:property name="upperLegWidth" value="0.015" />
	<xacro:property name="upperLegLength" value="0.015" />
	<xacro:property name="upperLegHeight" value="0.142" />
	<xacro:property name="upperLegMass" value="0.2" />

	<xacro:property name="lowerLegWidth" value="0.015" />
	<xacro:property name="lowerLegLength" value="0.015" />
	<xacro:property name="lowerLegHeight" value="0.125" />
	<xacro:property name="lowerLegMass" value="0.08" />

	<xacro:property name="footWidth" value="0.015" />
	<xacro:property name="footLength" value="0.050" />
	<xacro:property name="footHeight" value="0.008" />
	<xacro:property name="footMass" value="0.01" />

	<xacro:property name="legDistFromCenter" value="0.015" />

	<xacro:property name="footAnklePos" value="0.015" />
	<xacro:property name="legAnklePos" value="0" />
	<xacro:property name="lowerKneePos" value="0.0.12" />
	<xacro:property name="upperKneePos" value="0.02" />
	<xacro:property name="legHipPos" value="0.0132" />
	<xacro:property name="bodyHipHigth" value="0.01" />
	<xacro:property name="bodyHipDepth" value="0.025" />
	<xacro:property name="massJointBodyDepth" value="0.07" />
	<xacro:property name="massJointBodyHeight" value="0.055" />
	<xacro:property name="massJointMassDepth" value="0.065" />
	<xacro:property name="massJointMassHeigth" value="0.007" />

	<xacro:property name="armLength" value="0.6" />
	<xacro:property name="armOffset" value="0.025" />


	<!-- Import Gazebo customizations and colors-->
	<xacro:include filename="$(find dacbot_description)/urdf/dacbot.gazebo" />
	<xacro:include filename="$(find dacbot_description)/urdf/colors.xacro" />


	<!-- Used for fixing robot to Gazebo 'base_link' -->
	<link name="world"/>

	<joint name="fixed_left" type="fixed">
		<parent link="world"/>
		<child link="left_foot"/>
	</joint>

	<!-- 
		Macros
	 -->

	 <!-- Box Macro! 
	<xacro:box name="" origin_x="" origin_y="" origin_z="" width="" length="" height="" mass="" />
	 -->
	<xacro:macro name="create_box" params="name origin_x origin_y origin_z width length height mass">
		<link name="${name}">
			<collision>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>
				<geometry>
					<box size="${width*scale} ${length*scale} ${height*scale}" />
				</geometry>
			</collision>

			<visual>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>
				<geometry>
					<box size="${width*scale} ${length*scale} ${height*scale}" />
				</geometry>
				<material name="orange"/>
			</visual>

			<inertial>
				<origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0"/>
				<mass value="${mass}"/>
				<inertia
					ixx="${mass / 12.0 * (length*length + height*height)*scale*scale}" ixy="0.0" ixz="0.0" 
					iyy="${mass / 12.0 * (height*height + width*width)*scale*scale}" iyz="0.0" 
					izz="${mass / 12.0 * (width*width + length*length)*scale*scale}"/>
			</inertial>
		</link>
	</xacro:macro>

	<!-- 
		Left Leg
	-->

	<!-- Left Foot -->
	<xacro:property name="var" value="1"/>
	<xacro:create_box name="left_foot" origin_x="${var}" origin_y="${footLength*scale/2 - footAnklePos}" origin_z="${footHeight/2}" width="${footWidth}" length="${footLength}" height="${footHeight}" mass="${footMass}" />

	<!-- Left Foot -->
	<xacro:property name="var" value"${var} + 1"/>
	<xacro:create_box name="left_lower_leg" origin_x="${var}" origin_y="${footLength*scale/2 - footAnklePos}" origin_z="${footHeight/2}" width="${footWidth}" length="${footLength}" height="${footHeight}" mass="${footMass}" />


	<!-- Left Lower Leg -->
	<!--
	<link name="left_lower_leg">
		<collision>
			<origin xyz="${-legDistFromCenter} 0 ${footHeight + lowerLegHeight*scale/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${lowerLegWidth*scale} ${lowerLegLength*scale} ${lowerLegHeight*scale}" />
			</geometry>
		</collision>

		<visual>
			<origin xyz="${-bodyWidth/2} 0 ${footHeight + lowerLegHeight/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${lowerLegWidth*scale} ${lowerLegLength*scale} ${lowerLegHeight*scale}" />
			</geometry>
			<material name="orange"/>
		</visual>

		<inertial>
			<origin xyz="${-bodyWidth/2} 0 ${footHeight + lowerLegHeight/2}" rpy="0 0 0"/>
			<mass value="${footMass}"/>
			<inertia
				ixx="${footMass / 12.0 * (lowerLegWidth*lowerLegWidth + lowerLegHeight*lowerLegHeight)}" ixy="0.0" ixz="0.0" 
				iyy="${footMass / 12.0 * (lowerLegHeight*lowerLegHeight + lowerLegWidth*lowerLegWidth)}" iyz="0.0" 
				izz="${footMass / 12.0 * (lowerLegWidth*lowerLegWidth + lowerLegWidth*lowerLegWidth)}"/>
		</inertial>
	</link>

	<joint name="left_ankle" type="fixed">
		<parent link="left_foot"/>
		<child link="left_lower_leg"/>
	</joint>
-->


</robot>
