<?xml version="1.0"?>

<robot name="dacbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Constants -->
	<xacro:property name="PI" value="3.1415926535897931"/>

	<!-- Robot configuration 
		Width = X axis
		Length = Y axis
		Height = Z axis
	-->
	<xacro:property name="scale" value="1" />

	<xacro:property name="bodyWidth" value="0.085" />
	<xacro:property name="bodyLength" value="0.08" />
	<xacro:property name="bodyHeight" value="0.065" />
	<xacro:property name="bodyMass" value="0.45" />

	<xacro:property name="weightWidth" value="0.05" />
	<xacro:property name="weightLength" value="0.07" />
	<xacro:property name="weightHeight" value="0.025" />
	<xacro:property name="weightMass" value="0.50" />

	<xacro:property name="upperLegLength" value="0.0142" />
	<xacro:property name="upperLegThickness" value="0.015" />
	<xacro:property name="upperLegMass" value="0.2" />

	<xacro:property name="lowerLegLength" value="0.0125" />
	<xacro:property name="lowerLegThickness" value="0.015" />
	<xacro:property name="lowerLegMass" value="0.08" />

	<xacro:property name="footWidth" value="0.015" />
	<xacro:property name="footLength" value="0.050" />
	<xacro:property name="footHeight" value="0.008" />
	<xacro:property name="footMass" value="0.01" />

	<xacro:property name="legDistFromCenter" value="0.015" />

	<xacro:property name="footAnklePos" value="0.015" />
	<xacro:property name="legAnklePos" value="0" />
	<xacro:property name="lowerKneePos" value="0.0.12" />
	<xacro:property name="upperKneePos" value="0.02" />
	<xacro:property name="legHipPos" value="0.0132" />
	<xacro:property name="bodyHipHigth" value="0.01" />
	<xacro:property name="bodyHipDepth" value="0.025" />
	<xacro:property name="massJointBodyDepth" value="0.07" />
	<xacro:property name="massJointBodyHeight" value="0.055" />
	<xacro:property name="massJointMassDepth" value="0.065" />
	<xacro:property name="massJointMassHeigth" value="0.007" />

	<xacro:property name="armLength" value="0.6" />
	<xacro:property name="armOffset" value="0.025" />


	<!-- Import Gazebo customizations and colors-->
	<xacro:include filename="$(find dacbot_description)/urdf/dacbot.gazebo" />
	<xacro:include filename="$(find dacbot_description)/urdf/colors.xacro" />


	<!-- Used for fixing robot to Gazebo 'base_link' -->
	<link name="world"/>

	<joint name="fixed_left" type="fixed">
		<parent link="world"/>
		<child link="left_foot"/>
	</joint>

	<joint name="fixed_right" type="fixed">
		<parent link="world"/>
		<child link="right_foot"/>
	</joint>

	<!-- 
		Left Leg
	-->

	<!-- Left Foot -->
	<link name="left_foot">
		<collision>
			<origin xyz="${-bodyWidth/2} 0 ${footHeight/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${footWidth*scale} ${footLength*scale} ${footHeight*scale}" />
			</geometry>
		</collision>

		<visual>
			<origin xyz="${-bodyWidth/2} 0 ${footHeight/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${footWidth*scale} ${footLength*scale} ${footHeight*scale}" />
			</geometry>
			<material name="orange"/>
		</visual>

		<inertial>
			<origin xyz="${-bodyWidth/2} 0 ${footHeight/2}" rpy="0 0 0"/>
			<mass value="${footMass}"/>
			<inertia
				ixx="${footMass / 12.0 * (footWidth*footWidth + footHeight*footHeight)}" ixy="0.0" ixz="0.0" 
				iyy="${footMass / 12.0 * (footHeight*footHeight + footWidth*footWidth)}" iyz="0.0" 
				izz="${footMass / 12.0 * (footWidth*footWidth + footWidth*footWidth)}"/>
		</inertial>
	</link>



	<!-- 
		Right Leg
	-->

	<!-- Right Foot -->
	<link name="right_foot">
		<collision>
			<origin xyz="${bodyWidth/2} 0 ${footHeight/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${footWidth*scale} ${footLength*scale} ${footHeight*scale}" />
			</geometry>
		</collision>

		<visual>
			<origin xyz="${bodyWidth/2} 0 ${footHeight/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${footWidth*scale} ${footLength*scale} ${footHeight*scale}" />
			</geometry>
			<material name="orange"/>
		</visual>

		<inertial>
			<origin xyz="${bodyWidth/2} 0 ${footHeight/2}" rpy="0 0 0"/>
			<mass value="${footMass}"/>
			<inertia
				ixx="${footMass / 12.0 * (footWidth*footWidth + footHeight*footHeight)}" ixy="0.0" ixz="0.0" 
				iyy="${footMass / 12.0 * (footHeight*footHeight + footWidth*footWidth)}" iyz="0.0" 
				izz="${footMass / 12.0 * (footWidth*footWidth + footWidth*footWidth)}"/>
		</inertial>
	</link>

</robot>
